-- =====================================================================
-- TheLook E-commerce SQL Business Analytics
-- Section: Customer Segmentation & Retention
-- Dataset: bigquery-public-data.thelook_ecommerce
-- =====================================================================

-- q10: Compare customer segments based on purchase frequency and revenue contribution.
with customer_summary as (
select user_id, count(distinct order_id) as total_orders,sum(sale_price) as total_revenue
from `bigquery-public-data.thelook_ecommerce.order_items`
group by user_id)
select case when total_orders = 1 then 'One-time Customer' else 'Repeat Customer' end as customer_type, count(*) as number_of_customers, round(sum(total_revenue),2) as total_revenue, round(avg(total_revenue),2) as avg_revenue_per_customer
from customer_summary
group by customer_type;

-- q18: No. of customers fall into each revenue segment, and how much revenue does each segment generate.
with customer_details as (
select user_id, sum(sale_price) as total_revenue
from `bigquery-public-data.thelook_ecommerce.order_items`
group by user_id),
segments as (
select case when total_revenue < 200 then 'Low Value' when total_revenue < 500 then 'Medium Value' when total_revenue < 1000 then 'High Value' else 'VIP' end as customer_segment, user_id, total_revenue
from customer_details)
select customer_segment, count(*) as customers, round(sum(total_revenue),2) as net_revenue, round(avg(total_revenue),2) as avg_revenue, round(count(*)*100/(
select count(*)
from segments),2) as customer_share_percentage
from segments
group by customer_segment
order by case customer_segment when 'Low Value' then 1 when 'Medium Value' then 2 when 'High Value' then 3 when 'VIP' then 4 end;

-- q19: For each month, how many unique customers placed orders and how much revenue did they generate.
with customer_details as (
select date_trunc(date(o.created_at),month) as month, count(distinct o.user_id) as active_customers, sum(oi.sale_price) as monthly_revenue
from `bigquery-public-data.thelook_ecommerce.orders` o
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by month
order by month)
select format_date('%B %Y', month) as months, active_customers, round(monthly_revenue,2) as monthly_sales,round(monthly_revenue/active_customers,2) as revenue_per_customer
from customer_details;

-- q20: For each month, how many customers were new customers and how many were repeat customers.
with first_order as (
select user_id, min(date(created_at)) as first_order_date
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
customer_month as (
select distinct o.user_id, date_trunc(date(o.created_at),month) as order_month,date_trunc(fo.first_order_date, month) as first_order_month
from `bigquery-public-data.thelook_ecommerce.orders` o
  join first_order fo
  on o.user_id = fo.user_id)
select format_date('%B %Y', order_month) as months, countif(order_month = first_order_month) as new_customers, countif(order_month > first_order_month) as repeat_customers, count(*)as total_active_customers
from customer_month
group by order_month
order by order_month;

-- q21: For each month, how much revenue was generated by new vs repeat customers.
with first_order as (
select user_id, date_trunc(date(min(created_at)),month) as first_month
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
customer_orders as (
select o.user_id, date_trunc(date(o.created_at),month) as order_month, fo.first_month, oi.sale_price
from `bigquery-public-data.thelook_ecommerce.orders` o
  join first_order fo
  on o.user_id = fo.user_id
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id)
select format_date('%B %Y', order_month) as months,round(sum(case when order_month = first_month then sale_price else 0 end),2) as new_customer_revenue, round(sum(case when order_month > first_month then sale_price else 0 end),2) as repeat_customer_revenue,round(sum(sale_price),2) as total_revenue
from customer_orders
group by order_month
order by order_month;

-- q22: For each month, how much is the average order value for new vs repeat customers.
with first_order as (
select user_id, date_trunc(date(min(created_at)), month) as first_month
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
order_details as (
select o.order_id, o.user_id, date_trunc(date(o.created_at), month) as order_month, fo.first_month, sum(oi.sale_price) as order_value
from `bigquery-public-data.thelook_ecommerce.orders` o
  join first_order fo
  on o.user_id = fo.user_id
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by o.order_id, o.user_id, order_month, fo.first_month)
select format_date('%b %Y', order_month) as month, round(safe_divide(sum(case when order_month = first_month then order_value else 0 end), count(distinct case when order_month = first_month then order_id end)), 2) as new_customer_aov, round(safe_divide(sum(case when order_month > first_month then order_value else 0 end), count(distinct case when order_month > first_month then order_id end)), 2) as repeat_customer_aov
from order_details
group by order_month
order by order_month;

-- q23: How much out of active customers each month were repeat customers.
with first_order as (
select user_id, date_trunc(date(min(created_at)), month) as first_month
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
customer_month as (
select distinct o.user_id, date_trunc(date(o.created_at), month) as order_month, fo.first_month
from `bigquery-public-data.thelook_ecommerce.orders` o
  join first_order fo
  on o.user_id = fo.user_id)
select format_date('%b %Y', order_month) as month, count(*) as active_customers, countif(order_month > first_month) as repeat_customers, round(safe_divide(countif(order_month > first_month) * 100, count(*)), 2) as repeat_customer_rate
from customer_month
group by order_month
order by order_month;

-- q24: How did new and repeat customer revenue change month-over-month.
with first_order as (
select user_id, date_trunc(date(min(created_at)), month) as first_month
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
monthly_revenue as (
select date_trunc(date(o.created_at), month) as month, sum(case when date_trunc(date(o.created_at), month) = fo.first_month then oi.sale_price else 0 end) as new_revenue, sum(case when date_trunc(date(o.created_at), month) > fo.first_month then oi.sale_price else 0 end) as repeat_revenue
from `bigquery-public-data.thelook_ecommerce.orders` o
  join first_order fo
  on o.user_id = fo.user_id
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by month),
growth as (
select month, new_revenue, repeat_revenue, lag(new_revenue) over(
order by month) as prev_new_revenue, lag(repeat_revenue) over(
order by month) as prev_repeat_revenue
from monthly_revenue)
select format_date('%b %Y', month) as months, round(new_revenue, 2) as new_revenue, round(repeat_revenue, 2) as repeat_revenue,round(safe_divide(new_revenue - prev_new_revenue, prev_new_revenue) * 100, 2) as new_revenue_mom, round(safe_divide(repeat_revenue - prev_repeat_revenue, prev_repeat_revenue) * 100, 2) as repeat_revenue_mom
from growth
order by month;

-- q34: How does purchase frequency vary across customer segments.
with customer_orders as (
select user_id, count(distinct order_id) as total_orders
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id)
select case when total_orders = 1 then 'one-time' when total_orders between 2 and 3 then 'occasional' when total_orders between 4 and 6 then 'frequent' else 'loyal' end as customer_segment, count(*) as customers, round(avg(total_orders), 2) as avg_orders_per_customer
from customer_orders
group by customer_segment
order by avg_orders_per_customer desc;

-- q36: Which customers are high-value, loyal, recently active, or at risk.
with customer_summary as (
select o.user_id, max(date(o.created_at)) as last_order_date, count(distinct o.order_id) as total_orders, sum(oi.sale_price) as total_revenue
from `bigquery-public-data.thelook_ecommerce.orders` o
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by o.user_id)
select user_id, date_diff(current_date(), last_order_date, day) as days_since_last_order, total_orders, round(total_revenue, 2) as total_revenue,case when date_diff(current_date(), last_order_date, day) <= 30 and total_orders >= 5 and total_revenue >= 500 then 'high value active' when date_diff(current_date(), last_order_date, day) <= 90 and total_orders >= 3 then 'loyal' when date_diff(current_date(), last_order_date, day) > 180 then 'at risk' else 'standard' end as customer_segment
from customer_summary;

-- q37: How many customers are active, at risk, or inactive based on their most recent order.
with customer_orders as (
select user_id, max(date(created_at)) as last_order_date
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id)
select case when date_diff(current_date(), last_order_date, day) <= 180 then 'active' when date_diff(current_date(), last_order_date, day) <= 550 then 'at risk' else 'inactive' end as customer_status, count(*) as customers
from customer_orders
group by customer_status
order by customers desc;

-- q38: How much historical revenue came from active, at-risk, and inactive customers.
with customer_summary as (
select o.user_id, max(date(o.created_at)) as last_order_date, sum(oi.sale_price) as total_revenue
from `bigquery-public-data.thelook_ecommerce.orders` o
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by o.user_id)
select case when date_diff(current_date(), last_order_date, day) <= 180 then 'active' when date_diff(current_date(), last_order_date, day) <= 550 then 'at risk' else 'inactive' end as customer_status, count(*) as customers, round(sum(total_revenue), 2) as revenue
from customer_summary
group by customer_status
order by revenue desc;

-- q39: What is the average lifetime revenue generated by customers in each activity segment.
with customer_summary as (
select o.user_id, max(date(o.created_at)) as last_order_date, sum(oi.sale_price) as total_revenue
from `bigquery-public-data.thelook_ecommerce.orders` o
  join `bigquery-public-data.thelook_ecommerce.order_items` oi
  on o.order_id = oi.order_id
group by o.user_id)
select case when date_diff(current_date(), last_order_date, day) <= 180 then 'active' when date_diff(current_date(), last_order_date, day) <= 550 then 'at risk' else 'inactive' end as customer_status, count(*) as customers, round(avg(total_revenue), 2) as avg_customer_lifetime_value, round(sum(total_revenue), 2) as total_revenue
from customer_summary
group by customer_status
order by avg_customer_lifetime_value desc;

-- q40: What percentage of customers acquired in each month made another purchase within 30 days.
with first_order as (
select user_id, min(date(created_at)) as first_order_date
from `bigquery-public-data.thelook_ecommerce.orders`
group by user_id),
customer_orders as (
select f.user_id, f.first_order_date, date_trunc(f.first_order_date, month) as acquired_month, date(o.created_at) as order_date
from first_order f
  join `bigquery-public-data.thelook_ecommerce.orders` o
  on f.user_id = o.user_id)
select format_date('%B %Y', acquired_month) as acquired_months, count(distinct user_id) as customers_acquired, format_date('%B %Y', date_add(acquired_month, interval 1 month)) as next_month, count(distinct case when date_diff(order_date, first_order_date, day) between 1 and 30 then user_id end) as retention_nxt30_days, round(safe_divide(count(distinct case when date_diff(order_date, first_order_date, day) between 1 and 30 then user_id end) * 100, count(distinct user_id)), 2) as retention_rate
from customer_orders
group by acquired_month
order by acquired_month;

-- q41: What is the average number of days between purchases for repeat customers.
with customer_orders as (
select user_id, date(created_at) as order_date, lag(date(created_at)) over(
partition by user_id
order by created_at) as previous_order_date
from `bigquery-public-data.thelook_ecommerce.orders`)
select round(avg(date_diff(order_date, previous_order_date, day)), 2) as avg_days_between_orders
from customer_orders
where previous_order_date is not null;

